### ISSUE TITLE
Automate publishing with a script

### ISSUE THREAD

**Issue by renatodeleao** [whitesmith/Flooper.js#10]
there must be a way to automate version update tasks:
- bump version in package.json
- write a tag/milestone wtv commit (i never understood this, can someone explain me like i'm 5?)
- push to repo publish to npm and deploy site (already done `npm run deploy:site`)  

Any help would be appreciated.

**Comment by mgontav** [comment]
https://docs.npmjs.com/getting-started/publishing-npm-packages

https://yarnpkg.com/lang/en/docs/cli/publish/

Basically the `npm`/`yarn` CLI already takes care of this for you, you just specify the version number and it writes to `package.json` and tags your git repo.

IMO, deploying the site and the package should different things (what if you want to add examples to the site and don't change anything on the package? or fix some bugs on the package that really don't affect the site?).

**Comment by renatodeleao** [comment]
@mgontav thanks for the enlightenment 🇮🇳 . Yup the script is already named `npm run deploy:site` for a reason i just didn't express myself right :p Will update as soon as i get the setup done.

If i got stuck, i'll let you know!

**Comment by renatodeleao** [comment]
Now we just need #4 to make this public.
