### ISSUE TITLE
Responsive update

### ISSUE THREAD

**Issue by renatodeleao** [whitesmith/Flooper.js#13]
If size of flooper elements change with media queries we need to recalc offsets.

**Comment by tomasmcm** [comment]
Is this necessary? won't `block.getBoundingClientRect();` always get the current size of an element?

**Comment by renatodeleao** [comment]
You're right. But maybe we should cache block sizes instead of calculating it on each `frameAnimation`. Should be better for perf. Hmm marked as enhancement.
