### ISSUE TITLE
Speaking of performance...

### ISSUE THREAD

**Issue by renatodeleao** [whitesmith/Flooper.js#22]
# Expected behavior and actual behavior.
I expect to not load a 10mb image from any website in the world without explicit consent.
Actually i'm loading 10mb each time i visit the website.

# Steps to reproduce the problem.
Visit the website.

# DEMO
![Dramatic](https://d26dzxoao6i3hh.cloudfront.net/items/1m1x3g2F0D0i2I0Z1x2V/%5B661e20e693de1fee8258c78b9f8ed083%5D_Image+2017-12-08+at+6.39.38+PM.png?v=6c27e973)

**Comment by tomasmcm** [comment]
![](https://media.giphy.com/media/3oEduNITi4GfwxY1Fu/giphy.gif)
![](https://media.giphy.com/media/xT0BKFyZt9MMx9xkpW/giphy.gif)

**Comment by tomasmcm** [comment]
Fixed in https://github.com/whitesmith/flooper/pull/21
